### ISSUE TITLE
No function at all

### ISSUE THREAD

**Issue by damuellen** [MFranceschi6/vscode-swift-test-adapter#1]
Hello,
Unfortunately, the extension does nothing for me under Linux.
I have tried Swift 5.3.3 and 5.4, the testing window is empty and I don't get an error message. Can you help me further.

**Comment by MFranceschi6** [comment]
Hi yes of course.
I currently have installed swift 5.3.3 and I didn't tried the 5.4 version
In the test tab you should see the reload icon.
I suppose you already tried to click on it but you never know.
In your output window you should also be able to select the `Swift test explorer` which prints debug India about builds and tests.
Could you confirm this and also paste that log
Thanks

**Comment by damuellen** [comment]
I only have `Test Explorer` no `Swift test explorer` but its empty.
The reload icon is spinning all the time.

**Comment by damuellen** [comment]
Maybe I should note im using Github Codespaces.

**Comment by MFranceschi6** [comment]
Ok, today I've tried the extension with swift 5.4 and I also have the never-ending spinning reload icon.
I will fix this in the next few days.

In the extensions settings, you can enable the `Swift Test Explorer` log.
Can you do it and post what you see.
Could you also run
```
swift test --enable-test-discovery -l
```
in your terminal and confirm that it doesn't produce errors

Thank you.

I actually don't know what interaction the extension has with Github Codespaces.

**Comment by MFranceschi6** [comment]
I've released a new version which should address the issue with swift 5.4 and also fixed some bugs in detecting the tests. You can update the extension and let me know if anything changed

**Comment by damuellen** [comment]
Thank you for the quick update. The extension now works for me too.
