### ISSUE TITLE
Seems to assume test targets are nested under Tests/

### ISSUE THREAD

**Issue by tmandry** [MFranceschi6/vscode-swift-test-adapter#2]
I think this layout comes from Xcode, but it is not the default for native Swift packages. My test target is in the folder of the same name under `Sources/`. See my [Package.swift](https://github.com/tmandry/x3/blob/master/Package.swift) for an example.

**Comment by 0xTim** [comment]
It is the de facto standard for native Swift packages. See [Swift NIO](https://github.com/apple/swift-nio) as an example or even [SwiftPM](https://github.com/apple/swift-package-manager)

**Comment by 0xTim** [comment]
(Regardless is should probably try and get the test sources from SwiftPM but having it under `Tests/` is a sensible default)

**Comment by MFranceschi6** [comment]
Hi,
I'm very sorry for some reasons I've missed this issue.

And you are right it actually assumes the tests to be in the `Test/` directory I honestly thought that tests had to go there for the project to build.
If you run
`swift test --enable-test-discovery -l`
Does it correctly shows your tests?


I will correct this behavior asap

**Comment by MFranceschi6** [comment]
Hello,
I should have resolved this problem with this fix.

Let me know if you are now able to see your tests.
I wasn't able to build your project under linux using swiftpm so I'm not sure if this will solve your problems

Feel free to open a new issue
